name: Verification

on:
  pull_request:
  workflow_dispatch:

jobs:

  check_compilation:
    name: Check compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run compilation
        run: |
          make

  run_tests:
    name: Run tests
    needs: [check_compilation]
    timeout-minutes: 2
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          make tests_run
